# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_Students.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QMessageBox 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 771, 591))
        self.label.setStyleSheet("background-color: rgb(44, 132, 132);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 781, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 80, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 140, 281, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 180, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 200, 281, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 260, 281, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 300, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 320, 281, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(290, 370, 271, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 400, 171, 171))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 450, 151, 41))
        self.pushButton.clicked.connect(self.UploadImage) # This function is for Upload image 
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(163, 118, 107);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 450, 151, 41))
        self.pushButton_2.clicked.connect(self.AddData) # This function is for the add data
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(163, 118, 107);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add_Students Screen"))
        self.label_2.setText(_translate("MainWindow", "Pleas Add Here Students who\'s Come New One"))
        self.label_3.setText(_translate("MainWindow", "First Name *"))
        self.label_4.setText(_translate("MainWindow", "Last Name *"))
        self.label_5.setText(_translate("MainWindow", "Father Name *"))
        self.label_6.setText(_translate("MainWindow", "Roll No *"))
        self.label_7.setText(_translate("MainWindow", "Email *"))
        self.checkBox.setText(_translate("MainWindow", "Remember Me "))
        self.pushButton.setText(_translate("MainWindow", "Upload Image"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Data"))

# This function is for Upload image 
    def UploadImage(self):
        print("yes! Upload Image Successfully!")
        file_path, _ = QFileDialog.getOpenFileName(None, "Select Image", "", "Images (.png *.xpm *.jpg *.jpeg)")
        if file_path:
            self.label_8.setPixmap(QtGui.QPixmap(file_path)) # For display image
            self.image_path = file_path

# This function is for the add data
    def AddData(self):
        print("Yes! Data Add Successfully.")
        fname = self.lineEdit.text()
        print(fname)
        lname = self.lineEdit_2.text()
        print(lname)
        faname = self.lineEdit_3.text()
        print(faname)
        rollno = self.lineEdit_4.text()
        print(rollno)
        email = self.lineEdit_5.text()
        print(email)

# This condition for if you incorrect or not write something in the input field then show popup
        if fname == "" or lname == "" or faname == "" or rollno == "" or email == "":
            self.show_popup("Invalid Input", "Pleas fill all required fields.")
            return
        if "@" not in email:
            self.show_popup("Invalid Email", "Pleas enter a valid email address.")
            return

# Ensure image_path exists before accessing it
        if hasattr(self, 'image_path'):
            image_path = self.image_path  # Path to the image
        else:
            image_path = None

# These lines are used for connect python to the sql server
        conn = pyodbc.connect("Driver={SQL server};"
                        "Server=DESKTOP-D7G8TJI;"
                        "Database=School_Managementdb;"
                        "Trusted_Connection=yes;")
        cursor = conn.cursor()

# Read the image as image
        with open (self.image_path, "rb") as file:
            image = file.read()
        cursor.execute("INSERT INTO [School_ManagementTable] (First_Name, Last_Name, Father_Name, Roll_No, Email, Student_Image) VALUES (?, ?, ?, ?, ?, ?)",
        (fname, lname, faname, rollno, email, image_path))
        conn.commit()
        print("Data sent to Database Successfully!")
        self.show_popup("Success", "Data added successfully!")

# This function is for show popup message if not write something in the input field
    def show_popup(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Warning if "Invalid" in title else QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedWidth(770)
    MainWindow.setFixedHeight(590)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
