# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_SearchData.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 671, 571))
        self.label.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"background-color: rgb(203, 192, 186);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 671, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 100, 261, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("pic1.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 380, 141, 41))
        self.pushButton.clicked.connect(self.ShowAddScreen) # This function is for Go to Add students screen
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 380, 141, 41))
        self.pushButton_2.clicked.connect(self.ShowSearchScreen) # This function is for Go to search students screen
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add & Search Screen"))
        self.label_2.setText(_translate("MainWindow", "ADD & SERACH DATA IF YOU ADD OR FIND SOME STUDENTS"))
        self.pushButton.setText(_translate("MainWindow", "ADD DATA"))
        self.pushButton_2.setText(_translate("MainWindow", "SERACH DATA"))

# This function is for Go to Add students screen
    def ShowAddScreen(self):
        print("Yes! Go to the Add Screen.")
        from Add_Students import Ui_MainWindow as popupadd
        self.MainWindow2 = QtWidgets.QMainWindow()
        self.ui = popupadd()
        self.ui.setupUi(self.MainWindow2)
        self.MainWindow2.show()

    # This function is for Go to search students screen
    def ShowSearchScreen(self):
        print("Yes! Go to the Search Screen.")
        from Search_Students import Ui_MainWindow as popupsearch
        self.MainWindow3 = QtWidgets.QMainWindow()
        self.ui = popupsearch()
        self.ui.setupUi(self.MainWindow3)
        self.MainWindow3.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedWidth(670)
    MainWindow.setFixedHeight(570)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
