# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search_Students.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
import os
from PyQt5.QtWidgets import QMessageBox 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 671, 491))
        self.label.setStyleSheet("background-color: rgb(234, 164, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 671, 61))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 110, 301, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 180, 151, 41))
        self.pushButton.clicked.connect(self.SearchData) # This function is for Search Data
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 300, 171, 171))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 300, 171, 171))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search_Students Screen"))
        self.label_2.setText(_translate("MainWindow", "Find Here Student\'s Data Which You Add Before"))
        self.label_3.setText(_translate("MainWindow", "Search Student *"))
        self.pushButton.setText(_translate("MainWindow", "Search"))

# This function is for Search Data
    def SearchData(self):
        print("Yes! Find the Data Successfully.")
        rollno = self.lineEdit.text() # This is the for which write input field this show same as terminal
        print(rollno)
        search_text = self.lineEdit.text()

# This condition is for show popup if not write something in the input field

        if rollno == "":
            self.show_popup("Invalid Input", "Pleas first write roll no.")
    
# These lines are used for connect python to the sql server
        conn = pyodbc.connect("Driver={SQL server};"
                        "Server=DESKTOP-D7G8TJI;"
                        "Database=School_Managementdb;"
                        "Trusted_Connection=yes;")
        cursor = conn.cursor()

# This query for search data
        cursor.execute("SELECT First_Name, Last_Name, Father_Name, Roll_No, Email, Student_Image FROM [School_ManagementTable] WHERE Roll_No = ?", (search_text))
        result = cursor.fetchone()

# Check if a record was found or not
        if result:
            first_name, last_name, father_name, roll_no, email, user_image = result

# Display the data in the label_4
            self.label_4.setText(f"First_Name: {first_name} \nLast_Name: {last_name} \nFather_Name: {father_name} \nRoll_No: {roll_no} \nEmail: {email}")

# Check if the file exist or not
            if os.path.exists(user_image):
                pixmap = QtGui.QPixmap(user_image)
                self.label_5.setPixmap(pixmap) #Assuming label_5 is for the image
            else:
                print("Image File not Found!")
                self.label_5.setText("No Image Found!") # Opetional Fallback message
        else:
            print("No Matching Record Found!")
            self.label_4.setText("No Data Found!")

# # This function is for show popup if not write something in the input field
    def show_popup(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Warning if "Invalid" in title else QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedWidth(672)
    MainWindow.setFixedHeight(502)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
